#!/bin/bash

yum install java-17-amazon-corretto
java -version

cd /opt
wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
tar -xvzf apache-maven-3.9.9-bin.tar.gz
mv apache-maven-3.9.9 maven
./maven/bin/mvn -v

cd ~
echo 'M2_HOME=/opt/maven
M2=/opt/maven/bin
JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto.x86_64
PATH=$PATH:$HOME/bin:$JAVA_HOME:$M2_HOME:$M2
export PATH' >>  .bash_profile
source .bash_profile
echo $PATH
mvn -v

cd /opt
wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.97/bin/apache-tomcat-9.0.97.tar.gz
tar -xvzf apache-tomcat-9.0.97.tar.gz
mv apache-tomcat-9.0.97 tomcat
cd tomcat/bin

# insert comment signs before the found pattern
# use /i\ for insert, /a\ for append
sed -i '/<Valve className="org.apache.catalina.valves.RemoteAddrValve/i\<!--' /opt/tomcat/webapps/host-manager/META-INF/context.xml
sed -i '/<Manager/i\—>' /opt/tomcat/webapps/host-manager/META-INF/context.xml
sed -i '/<Valve className="org.apache.catalina.valves.RemoteAddrValve/i\<!--' /opt/tomcat/webapps/manager/META-INF/context.xml
sed -i '/<Manager/i\—>' /opt/tomcat/webapps/manager/META-INF/context.xml

# add text into a new temporary file
echo '<role rolename="admin-gui"/>
<role rolename="manager-gui"/>
<role rolename="manager-script"/>
<role rolename="manager-jmx"/>
<role rolename="manager-status"/>
<user username="admin" password="s3cret" roles="admin-gui,manager-gui,manager-script,manager-jmx,manager-status"/>' > /tmp/new_content.xml

# then add text from the new temp file into the tomcat-users.xml
sed -i '/version="1.0">/r /tmp/new_content.xml' /opt/tomcat/conf/tomcat-users.xml

ln -s /opt/tomcat/bin/startup.sh /usr/local/bin/tomcatup
ln -s /opt/tomcat/bin/startup.sh /usr/local/bin/tomcatdown

tomcatup

cd ~
mvn archetype:generate -DgroupId=vn.edu.rmit -DartifactId=helloWorld -DarchetypeArtifactId=maven-archetype-webapp -DinteractiveMode=false
cd helloWorld/

# may use " \ " to avoid error
sed -i '/<\/h2>/a\<h3>DevOps at RMIT<\/h3>' ~/helloWorld/src/main/webapp/index.jsp
mvn package
cp /root/helloWorld/target/helloWorld.war /opt/tomcat/webapps/

# potentially work after rebooting the server
sed -i 's/8080/80/g' /opt/tomcat/conf/server.xml

tomcatdown
tomcatup
